version: "3.8"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '4257:5000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npm start"
    restart: on-failure

  db:
    image: 'mongo'
    #container_name: 'my-mongo-container'
    env_file:
      - .env
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo_db:/data/db
    ports:
      - '27017-27019:27017-27019'
    restart: on-failure

  web:
    image: 'nginx:alpine'
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/share/nginx/html
    restart: on-failure
